name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
      -
        name: Check Out Repo B
        uses: actions/checkout@v4
        with:
          repository: joel/gem_b
          token: ${{ secrets.JOEL_PAT_1 || github.token }}
          path: gem_b
      -
        uses: actions/checkout@v4
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      -
        name: Run the default task
        run: bundle exec rake
